version: '3.7'

# HOW TO USE DOCKER-COMPOSE ? 
# docker-compose down
# docker-compose up -d --build --remove-orphans 
# docker-compose stop

services:

  # DATABSE configuration
  postgres:
    container_name: postgres-SQL-client
    image: postgres:9.4
    #restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 000000
      POSTGRES_DB: bdddragdrop
    ports: 
      - 5432:5432

  # FLASK Configuration
  flask-web-api:
    container_name: flask-api
    build: api
    ports:
        - "5000:5000"
    volumes:
        - myVolume:/data
    environment:
      #DATABASE_URL: postgresql://postgres:000000@localhost:5432/bdddragdrop
      #try this
      DATABASE_URL: postgresql://postgres:000000@postgres:5432/bdddragdrop
    depends_on:
      - postgres
  
      # SERVER npm configuration
  web:
    container_name: npm-web-server
    build: webapp
    command: npm run serve -d
    #volumes:
      #- .:/app
      #- app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:000000@localhost:5432/bdddragdrop
  
        #Client DB for postgres-SQL
  adminer:
    container_name: DB-Client
    image: adminer
    restart: always
    ports:
      - 1000:1000
    environment:
      ADMINER_DEFAULT_DB_HOST: root
      ADMINER_DEFAULT_DB_DRIVER: pgsql
    #depends_on:
      #- postgres

volumes:
  myVolume: