version: '3.7'

# HOW TO USE DOCKER-COMPOSE ? 
# docker-compose down
# docker-compose up -d # launch containers

#HELP 
# docker-compose up -d --build --remove-orphans  #launch containers with pre-build
# docker-compose stop
services:

  # DATABSE configuration
  postgres:
    container_name: postgres-SQL
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 000000
    ports: 
      - 5432
    
  # SERVER npm configuration
  web:
    container_name: npm-vue-web-server
    build: webapp
    command: npm run serve
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:000000@localhost:5432/bdddragdrop

  # FLASK Configuration
  flask-web-api:
    container_name: flask-web-server-api
    build: api
    ports:
        - "5000:5000"
    volumes:
        - .:/api

#volumes:
  #db_data: