version: '3.7'

# HOW TO USE DOCKER-COMPOSE ? 
# docker-compose down
# docker-compose up -d --build --remove-orphans 
# docker-compose stop

services:

  # DATABSE configuration
  postgres:
    container_name: postgres-SQL-client
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 000000
      POSTGRES_DB: bdddragdrop
    ports: 
      - 5432
    
  # SERVER npm configuration
  web:
    container_name: npm-web-server
    build: webapp
    command: npm run serve -d
    #volumes:
      #- .:/app
      #- app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:000000@localhost:5432/bdddragdrop

  # FLASK Configuration
  flask-web-api:
    container_name: flask-api
    build: api
    ports:
        - "5000:5000"
    #volumes:
        #- myVolume:/api
    environment:
      DATABASE_URL: postgresql://postgres:000000@localhost:5432/bdddragdrop
      LDFLAGS: -L/usr/local/opt/openssl/lib" export CPPFLAGS="-I/usr/local/opt/openssl/include

#volumes:
  #db_data: