version: '3.7'

# HOW TO USE  ? 
# docker-compose down
# docker-compose up -d # launch containers

#HELP 
# docker-compose up -d --build  #launch containers with pre-build
# docker-compose stop
services:

  # Flask-Vue-Docker-Kubernetes-Postgres : https://hub.docker.com/r/zorrowang/flask-vue-kubernetes_postgres/tags
  #zorrowang-containers:
    #image: zorrowang/flask-vue-kubernetes_postgres

  # DATABSE configuration
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 000000
    
  # SERVER npm configuration
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:000000@localhost:5432/bdddragdrop
  #npm-server:
    #container_name: NodeServerNPM
    #build: docker/Node


  #VUECLI configuration
  vuecli:
    container_name: VuedragdropDiagram
    build: docker/Vue
      #context: .
      #dockerfile: Vue/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'

  # FLASK Configuration
  flask-web-api:
        build: docker/Flask
        ports:
            - "5000:5000"
        volumes:
            - .:/api
        #depends_on:
            #- redis
    #redis:
        #image: redis

#volumes:
  #db_data: