"""empty message

Revision ID: b4ac2b9126d8
Revises: 
Create Date: 2020-12-02 20:43:24.233266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ac2b9126d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('node1', sa.String(length=4), nullable=True),
    sa.Column('node2', sa.String(length=4), nullable=True),
    sa.Column('functionNumber', sa.Integer(), nullable=True),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Integer(), nullable=True),
    sa.Column('Labels', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Record')
    op.drop_table('Label')
    # ### end Alembic commands ###
