"""empty message

Revision ID: d7a49c15dfed
Revises: 
Create Date: 2020-12-03 17:05:13.684381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a49c15dfed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('node1', sa.String(length=4), nullable=True),
    sa.Column('node2', sa.String(length=4), nullable=True),
    sa.Column('functionNumber', sa.Integer(), nullable=True),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('labels', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Record')
    op.drop_table('Label')
    # ### end Alembic commands ###
